require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmailAddressesController do

  # This should return the minimal set of attributes required to create a valid
  # EmailAddress. As you add validations to EmailAddress, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "address" => "MyString" , contact_id: 1, contact_type: "Person" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmailAddressesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET new" do
    it "assigns a new email_address as @email_address" do
      get :new, {}, valid_session
      assigns(:email_address).should be_a_new(EmailAddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested email_address as @email_address" do
      email_address = EmailAddress.create! valid_attributes
      get :edit, {:id => email_address.to_param}, valid_session
      assigns(:email_address).should eq(email_address)
    end
  end

  describe "POST create" do
    describe "with valid params" do

      let(:gary) { Person.create(first_name: 'Gary', last_name: 'Johnson') }
      let(:valid_attributes) { {address: '23423msn@msn.gov', contact_id: gary.id, contact_type: 'Person'} }
      it "creates a new EmailAddress" do
        expect {
          post :create, {:email_address => valid_attributes}, valid_session
        }.to change(EmailAddress, :count).by(1)
      end

      it "assigns a newly created email_address as @email_address" do
        post :create, {:email_address => valid_attributes}, valid_session
        assigns(:email_address).should be_a(EmailAddress)
        assigns(:email_address).should be_persisted
      end

      it "redirects to the email address' person" do
        gary = Person.create(first_name: 'Gary', last_name: 'Johnson')
        valid_attributes = {address: '23423msn@msn.gov', contact_id: gary.id, contact_type: 'Person'}
        post :create, {:email_address => valid_attributes}, valid_session
        expect(response).to redirect_to(gary)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved email_address as @email_address" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailAddress.any_instance.stub(:save).and_return(false)
        post :create, {:email_address => { "address" => "invalid value" }}, valid_session
        assigns(:email_address).should be_a_new(EmailAddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmailAddress.any_instance.stub(:save).and_return(false)
        post :create, {:email_address => { "address" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do

      let(:bob) { Person.create(first_name: 'Bob', last_name: 'Jones') }
      let(:valid_attributes) { {address: 'rrr@msn.com', contact_id: bob.id, contact_type: 'Person'} }
      it "updates the requested email_address" do
        email_address = EmailAddress.create! valid_attributes
        # Assuming there are no other email_addresses in the database, this
        # specifies that the EmailAddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmailAddress.any_instance.should_receive(:update).with({ "address" => "MyString" })
        put :update, {:id => email_address.to_param, :email_address => { "address" => "MyString" }}, valid_session
      end

      it "assigns the requested email_address as @email_address" do
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => valid_attributes}, valid_session
        assigns(:email_address).should eq(email_address)
      end

      it "redirects to the email_address person" do
        bob = Person.create(first_name: 'Bob', last_name: 'Jones')
        valid_attributes = {address: 'rrr@msn.com', contact_id: bob.id, contact_type: 'Person'}
        email_address = EmailAddress.create! valid_attributes
        put :update, {:id => email_address.to_param, :email_address => valid_attributes}, valid_session
        response.should redirect_to(bob)
      end
    end

    describe "with invalid params" do
      it "assigns the email_address as @email_address" do
        email_address = EmailAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => email_address.to_param, :email_address => { "address" => "invalid value" }}, valid_session
        assigns(:email_address).should eq(email_address)
      end

      it "re-renders the 'edit' template" do
        email_address = EmailAddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmailAddress.any_instance.stub(:save).and_return(false)
        put :update, {:id => email_address.to_param, :email_address => { "address" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    let(:jan) { Person.create(first_name: "Jan", last_name: "Fran") }
    let(:valid_attributes) { {address: "janfran@guv.edu", contact_id: jan.id, contact_type: 'Person' } }
    it "destroys the requested email_address" do
      email_address = EmailAddress.create! valid_attributes
      expect {
        delete :destroy, {:id => email_address.to_param}, valid_session
      }.to change(EmailAddress, :count).by(-1)
    end

    it "redirects to the email_addresses list" do
      email_address = EmailAddress.create! valid_attributes
      delete :destroy, {:id => email_address.to_param}, valid_session
      response.should redirect_to(jan)
    end
  end

end
